#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CinemaApp.Resource", IsApplication=true)]

namespace CinemaApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int fingerprint = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int videoIcon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int background = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int bookingPage = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int bookingPageMovieTitle = 2131034113;
			
			// aapt resource value: 0x7f050012
			public const int buttonBookTicket = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int buttonConfirmBooking = 2131034118;
			
			// aapt resource value: 0x7f050019
			public const int buttonSignUp = 2131034137;
			
			// aapt resource value: 0x7f050016
			public const int card = 2131034134;
			
			// aapt resource value: 0x7f050008
			public const int confirmBooking_buttonSubmit = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int confirmBooking_password = 2131034119;
			
			// aapt resource value: 0x7f050015
			public const int confirmPassword = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int cvv = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int dateSpinner = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int description = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int expDate = 2131034135;
			
			// aapt resource value: 0x7f05000a
			public const int loadingPanel = 2131034122;
			
			// aapt resource value: 0x7f050013
			public const int login = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int mainContainer = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int mask = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int password = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int root = 2131034121;
			
			// aapt resource value: 0x7f05001a
			public const int seats = 2131034138;
			
			// aapt resource value: 0x7f050004
			public const int seatslist = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int sessionsGrid = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int textViewDetails = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int textViewTitle = 2131034126;
			
			// aapt resource value: 0x7f050005
			public const int totalPrice = 2131034117;
			
			// aapt resource value: 0x7f050010
			public const int trailerButton = 2131034128;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BookingPageLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ConfirmBookingPageLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MoviePageLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegistrationPage = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SeatsScheme = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SpinnerItem = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
